services:
  app:
    build:
      context: ./backend
    ports:
      - "8082:8081"
    volumes:
      - ./data:/app/data



  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - "4445:4444"
