server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlite:./data/lostfound.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  thymeleaf:
    cache: false

app:
  seed:
    enabled: true
