spring:
  datasource:
    url: jdbc:sqlite:target/it-db.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
app:
  seed:
    enabled: false
